version: "3"
services:
  db:
    build: ./sql
    image: bb13-db:latest
    networks:
      - internal
    volumes:
      - "./sql/test_db:/var/lib/mysql"
  game:
    build: .
    image: bb13:latest
    networks:
      - internal
    ports:
      - "5000:5000"
networks:
  internal:
